### ISSUE TITLE
Assign action on "Try Face ID Again"

### ISSUE THREAD

**Issue by belmonmi** [andreas-nesheim/MauiBiometrics#1]
When face ID failed (non-matching) how to assign an action for "Try Face ID Again"? 
`FingerprintAuthenticationResult tmpAuthResult = await tmpFingerprint.AuthenticateAsync(tmpConf, CancellationToken.None);`
The AuthenticateAsync() method returns only on success or on cancel and does nothing on "Try Face ID Again". By the time I got control in my code I cannot detect what user wants.

Thank you,
Michael
![FaceNotRecognized](https://user-images.githubusercontent.com/67832959/183464152-d1ea4787-56b4-42c1-be1a-e31e950758b4.png)
.

**Comment by andreas-nesheim** [comment]
Hi! I'm not too sure if that's possible. I would ask the maintainer of the package or submit a issue/question on the repository: https://github.com/smstuebe/xamarin-fingerprint
